/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EsqueciSenhaC;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author eduar
 */
public class EsqueciSenhaView extends javax.swing.JFrame {
    
    private final EsqueciSenhaC controller;
    /**
     * Creates new form EsqueciSenhaView
     */
    public EsqueciSenhaView() {
        initComponents();
        controller = new EsqueciSenhaC(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldJogoFavorito = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmailSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldNovaSenha = new javax.swing.JPasswordField();
        jButtonTrocarSenha = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Esqueci a Senha");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trocar a Senha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 217, 34));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jogo favorito");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 52));
        getContentPane().add(jTextFieldJogoFavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 221, 37));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, 60));
        getContentPane().add(jTextFieldEmailSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 221, 37));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nova Senha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 52));
        getContentPane().add(jPasswordFieldNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 220, 40));

        jButtonTrocarSenha.setText("Trocar Senha");
        jButtonTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrocarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTrocarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/miranha.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrocarSenhaActionPerformed
        try {
            controller.trocarSenha();
        } catch (SQLException ex) {
            Logger.getLogger(EsqueciSenhaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTrocarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsqueciSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsqueciSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsqueciSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsqueciSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsqueciSenhaView().setVisible(true);
            }
        });
    }

    public JPasswordField getjPasswordFieldNovaSenha() {
        return jPasswordFieldNovaSenha;
    }

    public void setjPasswordFieldNovaSenha(JPasswordField jPasswordFieldNovaSenha) {
        this.jPasswordFieldNovaSenha = jPasswordFieldNovaSenha;
    }

    public JTextField getjTextFieldIDSenha() {
        return jTextFieldEmailSenha;
    }

    public void setjTextFieldIDSenha(JTextField jTextFieldIDSenha) {
        this.jTextFieldEmailSenha = jTextFieldIDSenha;
    }

    public JTextField getjTextFieldJogoFavorito() {
        return jTextFieldJogoFavorito;
    }

    public void setjTextFieldJogoFavorito(JTextField jTextFieldJogoFavorito) {
        this.jTextFieldJogoFavorito = jTextFieldJogoFavorito;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTrocarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordFieldNovaSenha;
    private javax.swing.JTextField jTextFieldEmailSenha;
    private javax.swing.JTextField jTextFieldJogoFavorito;
    // End of variables declaration//GEN-END:variables
}
