/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MenuNormalC;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author eduar
 */
public class MenuNormalView extends javax.swing.JFrame {
    
    private final MenuNormalC controller;
    /**
     * Creates new form Menuview
     */
    public MenuNormalView() {
        initComponents();
        controller = new MenuNormalC(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMUnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMUemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMUtelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldMUsenha = new javax.swing.JPasswordField();
        jButtonMUeditar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMUJogo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu NORMAL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 113, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 50, 30));

        jTextFieldMUnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMUnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMUnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 200, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 50, 30));

        jTextFieldMUemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMUemailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMUemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 80, 30));

        jTextFieldMUtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMUtelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMUtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 200, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 50, 30));
        getContentPane().add(jPasswordFieldMUsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 200, 30));

        jButtonMUeditar.setText("Editar");
        jButtonMUeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMUeditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMUeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 160, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jogo Favorito");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 120, 30));

        jTextFieldMUJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMUJogoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMUJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 200, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Senha é necessária para comprovar sua autenticidade");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 360, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Minecraft-Wallpapers-scaled.jpg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(1000, 700));
        jLabel8.setMinimumSize(new java.awt.Dimension(1000, 700));
        jLabel8.setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-710, 0, 1920, -1));
        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMUnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMUnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMUnomeActionPerformed

    private void jTextFieldMUemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMUemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMUemailActionPerformed

    private void jTextFieldMUtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMUtelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMUtelefoneActionPerformed

    private void jButtonMUeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMUeditarActionPerformed
        controller.editarNormal();
    }//GEN-LAST:event_jButtonMUeditarActionPerformed

    private void jTextFieldMUJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMUJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMUJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNormalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNormalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNormalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNormalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuNormalView().setVisible(true);
            }
        });
    }

    public JPasswordField getjPasswordFieldMUsenha() {
        return jPasswordFieldMUsenha;
    }

    public void setjPasswordFieldMUsenha(JPasswordField jPasswordFieldMUsenha) {
        this.jPasswordFieldMUsenha = jPasswordFieldMUsenha;
    }

    public JTextField getjTextFieldMUemail() {
        return jTextFieldMUemail;
    }

    public void setjTextFieldMUemail(JTextField jTextFieldMUemail) {
        this.jTextFieldMUemail = jTextFieldMUemail;
    }

    public JTextField getjTextFieldMUnome() {
        return jTextFieldMUnome;
    }

    public void setjTextFieldMUnome(JTextField jTextFieldMUnome) {
        this.jTextFieldMUnome = jTextFieldMUnome;
    }

    public JTextField getjTextFieldMUtelefone() {
        return jTextFieldMUtelefone;
    }

    public void setjTextFieldMUtelefone(JTextField jTextFieldMUtelefone) {
        this.jTextFieldMUtelefone = jTextFieldMUtelefone;
    }

    public JTextField getjTextFieldMUJogo() {
        return jTextFieldMUJogo;
    }

    public void setjTextFieldMUJogo(JTextField jTextFieldMUJogo) {
        this.jTextFieldMUJogo = jTextFieldMUJogo;
    }

   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMUeditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordFieldMUsenha;
    private javax.swing.JTextField jTextFieldMUJogo;
    private javax.swing.JTextField jTextFieldMUemail;
    private javax.swing.JTextField jTextFieldMUnome;
    private javax.swing.JTextField jTextFieldMUtelefone;
    // End of variables declaration//GEN-END:variables
}
